#!/bin/bash

# Jamie Carranza
# jamie.carranza@gmail.com
# February 26, 2011

# chkconfig: - 90 10
# description: Redhat style initialization script for a single Ruby/Sinatra process.
# processname: ruby www.rb

nagios-mobile='/usr/local/nagios/nagios-mobile/nagios-mobile.rb'
prog='nagios-mobile'
pidfile='/var/run/nagios-mobile.pid'
lockfile='/var/lock/subsys/nagios-mobile'
RETVAL='0'

. /etc/rc.d/init.d/functions

START () {
    echo -n $"Starting $prog: "
    daemon --pidfile=${pidfile} $nagios-mobile $OPTIONS
    RETVAL="$?"
    echo
    [ "$RETVAL" = 0 ] && touch ${lockfile}
    return $RETVAL
}

STOP () {
    echo -n $"Stopping $prog: "
    killproc -p ${pidfile} -d 10 $nagios-mobile
    RETVAL="$?"
    echo
    [ $RETVAL = 0 ] && rm -f ${lockfile} ${pidfile}
}

case $1 in
    start) START;;
    stop) STOP;;
    restart) STOP; START;;
esac

