#!/bin/bash

# chkconfig: - 90 10
# description: Redhat style initialization script for a single Ruby/Sinatra process.
# processname: ruby snowi.rb

APP='/usr/local/nagios/snowi/snowi.rb'
prog='snowi'
pidfile='/var/run/snowi.pid'
lockfile='/var/lock/subsys/snowi'
RETVAL='0'

#-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-

. /etc/rc.d/init.d/functions

START () {
    echo -n $"Starting $prog: "
    daemon --pidfile=${pidfile} $APP $OPTIONS
    RETVAL="$?"
    echo
    [ "$RETVAL" = 0 ] && touch ${lockfile}
    return $RETVAL
}

STOP () {
    echo -n $"Stopping $prog: "
    killproc -p ${pidfile} -d 10 $APP
    RETVAL="$?"
    echo
    [ $RETVAL = 0 ] && rm -f ${lockfile} ${pidfile}
}

case $1 in
    start) START;;
    stop) STOP;;
    restart) STOP; START;;
esac

